###
POST http://localhost:3000/api/v1/superheros HTTP/1.1
Content-Type: application/json

{
    "superhero":"batman",
    "universe":"Dc Comics",
    "superpowers":["Ninguno"],
    "creators": ["C1","C2"],
    "address":{
        "street": "Calle",
        "city":"Gótica",
        "state":"Caldas",
        "Country":"Colombia"
    }
}

###
GET http://localhost:3000/api/v1/superheros HTTP/1.1

###
GET http://localhost:3000/api/v1/users/

###
PUT http://localhost:3000/api/v1/superheros/63e577a77ac857a84b6cb201 HTTP/1.1
Content-Type: application/json

{
    "superhero":"batman",
    "universe":"Dc Comics",
    "superpowers":["Ninguno"],
    "creators": ["C1","C2"],
    "address":{
        "street": "Calle",
        "city":"Gótica",
        "state":"Caldas",
        "Country":"Colombia"
    }
}

###
DELETE http://localhost:3000/api/v1/superheros/63e5756716a048019efb8a14 HTTP/1.1

###
DELETE http://localhost:3000/api/v1/superheros/ HTTP/1.1

###
GET http://localhost:3000/api/v1/superheros/superpowers/2 HTTP/1.1

###
GET http://localhost:3000/api/v1/superheros/superpowers-list/superpowers HTTP/1.1
